import { Product } from "../types";

export const mockProducts: Product[] = [
  {
    id: 1,
    title: "Merrick Real Texas Beef + Sweet Potato Recipe Grain-Free Dry Dog Food, 25-lb bag",
    brand: "Merrick",
    price: 76.98,
    originalPrice: 89.99,
    autoshipPrice: 73.13,
    rating: 4.4,
    reviewCount: 2100,
    image: "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300",
    images: [
      "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=600",
      "https://images.unsplash.com/photo-1605568427561-40dd23c2acea?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=600",
    ],
    deal: true,
    flavors: ["Texas Beef + Sweet Potato", "Chicken + Sweet Potato", "Salmon + Sweet Potato"],
    sizes: [
      { name: "4-lb bag", price: 19.98, pricePerLb: "$4.99" },
      { name: "12-lb bag", price: 47.98, pricePerLb: "$4.00" },
      { name: "25-lb bag", price: 76.98, pricePerLb: "$3.08" },
    ],
    description: "Real deboned beef is always the first ingredient in this protein-rich recipe.",
    inStock: true,
    category: "dog-food",
    keywords: ["grain-free", "beef", "dog food", "dry food", "merrick"],
  },
  {
    id: 2,
    title: "Nature's Recipe Grain-Free Salmon, Sweet Potato & Pumpkin Recipe Dry Dog Food, 24-lb bag",
    brand: "Nature's Recipe",
    price: 49.98,
    originalPrice: 53.99,
    autoshipPrice: 47.48,
    rating: 4.6,
    reviewCount: 1700,
    image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300",
    images: [
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=600",
      "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=600",
    ],
    deal: true,
    flavors: ["Salmon, Sweet Potato & Pumpkin", "Chicken, Sweet Potato & Pumpkin", "Lamb, Sweet Potato & Pumpkin"],
    sizes: [
      { name: "4-lb bag", price: 12.98, pricePerLb: "$3.25" },
      { name: "12-lb bag", price: 29.98, pricePerLb: "$2.50" },
      { name: "24-lb bag", price: 49.98, pricePerLb: "$2.08" },
      { name: "34-lb bag", price: 67.98, pricePerLb: "$2.00" },
    ],
    description: "Real salmon is the first ingredient in this grain-free recipe made with sweet potatoes and pumpkin.",
    inStock: true,
    category: "dog-food",
    keywords: ["grain-free", "salmon", "dog food", "nature's recipe", "sweet potato"],
  },
  {
    id: 3,
    title: "Merrick Backcountry Raw Infused Grain-Free Great Plains Red Recipe Dry Dog Food, 22-lb bag",
    brand: "Merrick",
    price: 84.98,
    autoshipPrice: 80.73,
    rating: 4.2,
    reviewCount: 744,
    image: "https://images.unsplash.com/photo-1605568427561-40dd23c2acea?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300",
    images: [
      "https://images.unsplash.com/photo-1605568427561-40dd23c2acea?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=600",
    ],
    deal: true,
    flavors: ["Great Plains Red", "Pacific Catch", "Big Game"],
    sizes: [
      { name: "10-lb bag", price: 44.98, pricePerLb: "$4.50" },
      { name: "22-lb bag", price: 84.98, pricePerLb: "$3.86" },
    ],
    description: "Raw infused kibble with freeze-dried raw pieces for superior nutrition and taste.",
    inStock: true,
    category: "dog-food",
    keywords: ["grain-free", "raw infused", "dog food", "merrick", "backcountry"],
  },
  {
    id: 4,
    title: "Merrick Grain-Free Dry Dog Food Healthy Weight Recipe, 22-lb bag",
    brand: "Merrick",
    price: 72.98,
    autoshipPrice: 69.33,
    rating: 4.5,
    reviewCount: 791,
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300",
    images: [
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=600",
    ],
    deal: true,
    flavors: ["Healthy Weight", "Senior Recipe", "Puppy Recipe"],
    sizes: [
      { name: "12-lb bag", price: 42.98, pricePerLb: "$3.58" },
      { name: "22-lb bag", price: 72.98, pricePerLb: "$3.32" },
    ],
    description: "Reduced fat recipe perfect for weight management without sacrificing taste.",
    inStock: true,
    category: "dog-food",
    keywords: ["grain-free", "healthy weight", "dog food", "merrick", "weight management"],
  },
  {
    id: 5,
    title: "Blue Buffalo Freedom Complete & Balanced Adult Grain-Free Chicken & Potatoes Recipe, 24-lb bag",
    brand: "Blue Buffalo",
    price: 68.98,
    originalPrice: 76.99,
    autoshipPrice: 65.53,
    rating: 4.7,
    reviewCount: 2800,
    image: "https://images.unsplash.com/photo-1605568427561-40dd23c2acea?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300",
    images: [
      "https://images.unsplash.com/photo-1605568427561-40dd23c2acea?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=600",
    ],
    deal: true,
    flavors: ["Chicken & Potatoes", "Fish & Potatoes", "Lamb & Potatoes"],
    sizes: [
      { name: "11-lb bag", price: 39.98, pricePerLb: "$3.63" },
      { name: "24-lb bag", price: 68.98, pricePerLb: "$2.87" },
    ],
    description: "Made with real chicken and wholesome potatoes for dogs with food sensitivities.",
    inStock: true,
    category: "dog-food",
    keywords: ["grain-free", "chicken", "dog food", "blue buffalo", "freedom"],
  },
  {
    id: 6,
    title: "Natural Dog Treats Variety Pack - Grain-Free Training Treats",
    brand: "Chewy",
    price: 24.98,
    originalPrice: 29.99,
    autoshipPrice: 23.73,
    rating: 4.8,
    reviewCount: 1200,
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300",
    images: [
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=600",
    ],
    deal: true,
    flavors: ["Mixed Variety", "Chicken Only", "Salmon Only"],
    sizes: [
      { name: "16-oz pack", price: 24.98, pricePerLb: "$1.56" },
      { name: "32-oz pack", price: 42.98, pricePerLb: "$1.34" },
    ],
    description: "Premium training treats made with natural ingredients for positive reinforcement.",
    inStock: true,
    category: "dog-treats",
    keywords: ["grain-free", "treats", "training", "natural", "variety pack"],
  },
  {
    id: 7,
    title: "Premium Dental Chews for Large Dogs - Tartar Control",
    brand: "Dentley's",
    price: 34.98,
    autoshipPrice: 33.23,
    rating: 4.3,
    reviewCount: 856,
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300",
    images: [
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=600",
    ],
    deal: false,
    flavors: ["Original", "Mint Flavor"],
    sizes: [
      { name: "12-count", price: 19.98, pricePerLb: "$1.67" },
      { name: "24-count", price: 34.98, pricePerLb: "$1.46" },
    ],
    description: "Helps reduce tartar buildup and freshen breath with every chew.",
    inStock: true,
    category: "dog-treats",
    keywords: ["dental", "chews", "tartar control", "large dogs", "oral health"],
  },
  {
    id: 8,
    title: "Interactive Puzzle Feeder Bowl - Slow Feeding Solution",
    brand: "Outward Hound",
    price: 19.98,
    autoshipPrice: 18.98,
    rating: 4.6,
    reviewCount: 1543,
    image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300",
    images: [
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=600",
    ],
    deal: false,
    flavors: ["Blue", "Green", "Purple"],
    sizes: [
      { name: "Small", price: 15.98, pricePerLb: "N/A" },
      { name: "Medium", price: 19.98, pricePerLb: "N/A" },
      { name: "Large", price: 24.98, pricePerLb: "N/A" },
    ],
    description: "Makes mealtime fun while promoting healthier eating habits.",
    inStock: true,
    category: "dog-accessories",
    keywords: ["puzzle feeder", "slow feeding", "interactive", "bowl", "accessories"],
  },
];

export const chatResponses = [
  "I'd be happy to help you find the perfect pet products! What specific items are you looking for?",
  "Based on your question, I can recommend some great grain-free options that are popular with other pet parents.",
  "That's a great question! Let me show you some products that might be perfect for your pet's needs.",
  "I understand your concern. Here are some highly-rated products that address that specific need.",
  "For training puppies, I recommend starting with positive reinforcement and high-value treats. Would you like me to show you some training treat options?",
  "Grain-free diets can be beneficial for dogs with sensitivities. Let me filter the products to show you our best grain-free options.",
  "Dental health is so important! I can show you some great dental chews and toys that help maintain oral hygiene.",
  "Senior dogs have special nutritional needs. Would you like me to show you some senior-specific formulas?",
];
